apiVersion: 1

datasources:
  - name: PostgreSQL_JoomlaDB
    uid: PostgreSQL_JoomlaDB
    type: postgres
    access: proxy
    url: database:5432
    user: joomlauser
    secureJsonData:
      password: joomlapassword123
    database: joomladb
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
    isDefault: true
    editable: true